name: hotel
description: "App móvil de hotel con geolocalización y mapas en tiempo real."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- MAPAS ---
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # --- CHARTS / MEDIA / SENSORS / DB ---
  fl_chart: ^0.70.0
  camera: ^0.10.0
  video_player: ^2.5.1
  sensors_plus: ^7.0.0
  sqflite: ^2.2.8+4
  path: ^1.8.3
  path_provider: ^2.0.15

  # --- GEOLOCALIZACIÓN ---
  geolocator: ^13.0.2
  permission_handler: ^11.3.1

  # --- BASE DE DATOS EN TIEMPO REAL (Firebase) ---
  firebase_core: ^3.6.0
  firebase_database: ^11.1.4

  # --- ESTADO Y UTILIDADES ---
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
